---
- hosts: "{{ passed_in_hosts }}"
  become: true
  remote_user: ec2-user 
  become_user: root

  tasks:
    - name: install apache
      yum:
        name: httpd 
        state: present

    - name: Start and Enabled apache
      service: 
        name: httpd
        state: started
        enabled: yes